#+TITLE:       Cycle everything: why waste does not exist
#+AUTHOR:      andrea
#+EMAIL:       andrea-dev@hotmail.com
#+DATE:        2021-01-07 Thu
#+URI:         /blog/%y/%m/%d/cycle-everything-why-waste-does-not-exist
#+KEYWORDS:    energy, growth, society
#+TAGS:        energy, growth, society
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: Think about reusing anything that you think as waste!

#+begin_quote
We are stardust
We are golden
And we've got to get ourselves
Back to the garden

Woodstock by Joni Mitchell
#+end_quote

We are stardust. This is both romantic and scientifically reasonable.
It also reassures us that we will leave something valuable behind
anyway. Worst case scenario we become dust again (and maybe feed some
nice plants!).

Anything alive (us included) struggles to get along with the rest
sustainably.

The justification for this struggle always made me wonder: we
discovered with 2nd law of thermodynamics that the universe
must become more and more chaotic over time, so why do I feel the need
+to tidy up the house+ to make the world a better place? Am I not
supposed to generated waste anyway as a part of this chaotic universe?

As Fritjof Capra wrote in his fascinating book [[https://goodreads.com/book/show/314114.The_Web_of_Life?from_search=true&amp;from_srp=true&amp;qid=9NHVPDEfsE&amp;rank=1][The Web of Life]] (I
recommend you to read that yourself), living systems are open systems
that regulate themselves in disequilibrium. The difference between
stardust and alive stardust is that the latter organizes itself to
keep *good things in* and *bad things out*. Or, in other words, an
alive system filters the good stuff from chaos. They expel the unnecessary
stuff as new chaos.

This makes me feel better about recycling: indeed, it is a waste of
which is necessary until we get smarter. According to the principle
above, it is all about finding some life form that eat the stuff we
discard (no more splitting between plastic and paper bins, hurrah)!

For example, let's return to our dusty destiny: fungi and plants can
use dust and water to grow and they spread by feeding their fruits to
faster-moving life forms.

The other famous characteristic of life is that it always starves for
resources (avidity may end up be a feature). The most innovative forms
of life derive from scarcity. For example a theory of human evolution
is that we are just apes born prematurely, and because of our
incompleteness and scarcity of natural tools (like proper hair, claws
and [[https://www.youtube.com/watch?v=1wBYPjkGRdo][shooting claws]] even) we needed to compensate through
collaboration, forcing ourselves to make our own tools and emit sounds
to communicate which became later writing and started our history.

So life needs scarce and external resources to survive, it ingests
them, expels waste and repeats. This process is efficient and
sustainable in the sense that it repeats indefinitely. The cool thing
is that life reorganize itself to make this process more effective.
For example, think of the complex organization that our body displays
when our tongue rates something we put in our mouth as inedible.

And speaking about the tongue, it may have happened to you that when
you smell something delicious you also start salivating, craving for
that food to be yours as soon as possible. Well this brings us to
another interesting concept of life: a signal of an alive subsystem
that propagates and causes changes in the other subsystems in a
circular way. In our example, the nose brings particles of air to the
tongue, the tongue feels the taste, then salivation initiates, the
stomach gets ready to digest, the tongue gets the saliva and, well...
gets wet: do you see it? Something initiated from the tongue causes a
change to the state of the tongue itself.

In summary another property of life is also connectivity. Complex life
forms as plants, fungi, and us are aggregations of alive systems that
react to external signals. Any reaction modifies the subsystems and
the complex life form itself. The simplest example to consider is
your memory: the fact that you can recollect a previous experience is
an actual physical change of your body in terms of neurons and
synapses, and how this change happens is totally delegated to the
systems that compose you (a dream of efficiency for all managers).

Now let's get into why it is important for us and how mastering these
ideas can improve your daily life. Fritjof Capra writes: "A major
clash between economics and ecology derives from the fact that nature
is cyclical, whereas our industrial systems are linear". If any of
your manager (family included) ever pressured you to get your job done
quickly, well you have an example of linear approach. Overworking is
useless both for the low quality of the product and for the stress you
accumulate in the process. Both the side effects require maintenance.
While a business will pay the first, the latter is mostly on you:
[[https://ag91.github.io/blog/2020/09/26/life-is-short-but-not-short-enough-to-skip-planning/][crashing on the sofa exhausted]] is just your body recovering and paying
the price.

Instead, a periodic (i.e., cyclical) system is sustainable: you can
keep doing it indefinitely because you never exhaust your energy
levels. Our planet Earth is sustainable: cyclic seasons, cyclic water
supply, cyclic life and death, etc...

A periodic system has also another enviable characteristic:
predictability. For example, the snow-holidays business relies on the
seasons cycle to get ready to host tourists with skis and snowboard.

Anyway, predictability is a sweet spot for us because it allows us to
grow: if you know somebody serves lunch at midday every day, you can
skip food hunting and invest that saved time in some other way.

Indeed, you may use that extra time to compound yourself: improve the
quality of your work just a 0.1 % each workday and ripe the abundant
fruits of your improvement after some time.

And what other way you have to improve yourself other than... creating
your own cyclical system?! Indeed, you want to copy the marvellous
process of life because it is sustainable, predictable and
interconnected ([[https://ag91.github.io/blog/2020/12/12/life-is-a-cycle-why-periodic-behaviour-is-good-for-your-health/][I already wrote about that]]).

All in all, as alive beings we are better off [[file:/home/andrea/workspace/agenda/notes/20201227144754-standing_on_the_shoulders_of_giants.org][standing on the
shoulders of giants]], and, although we often think of these us some
smart people before us, I would suggest to skip the Lilliputians and
hang out with Life itself: slowly creating an ecosystem which values
waste as a resource [fn::one example I love is ducks slurping slugs: I
spent some time collecting slugs and moving them away from my loved
plants, but I could have saved time and fed some ducks at once instead!].
