#+TITLE:       Dignity, or why people are not goods
#+AUTHOR:      Andrea
#+EMAIL:       andrea-dev@hotmail.com
#+DATE:        2021-03-06 Sat
#+URI:         /blog/%y/%m/%d/dignity-or-why-people-are-not-goods
#+KEYWORDS:    society, growth
#+TAGS:        society, growth
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: Art and dignity to find ourselves

In the last few weeks I have been reading the thoughts of [[https://en.wikipedia.org/wiki/Tomaso_Montanari][Tomaso
Montanari]] and it has inspired me to look at art from a novel
perspective. All of a sudden I am discovering that art is more than
just a tension towards the beautiful, or a decoration, but rather a
gateway to understand what means to be human. I think this was quite
an enriching mental journey, so I decided to stimulate your thoughts
too.

My journey started from the association between pieces of art and
slavery. In Italy there is the tendency of looking at art as a source
of income. For example, it happens frequently enough that managers of
monumental venues rent out parts of these buildings for events
organized for rich people. The idea is that the income can flow into
the maintenance budget for the art piece. In this optic the value of
art pieces depends on how much interest the (touristic) market assigns
to them. An exemplary example is the Italian government sending a
fresco by Botticelli to foreign nations like China and [[http://www.ansamed.info/ansamed/it/notizie/stati/israele/2013/08/23/Arte-Annunciazione-Botticelli-arriva-Israele_9190183.html][Israel]] in order
to keep a good relationship.

However, we lost somewhere the context of this piece of art. The
context of this fresco is that it represents Saint Mary accepting
Jesus as her son. Botticelli painted this scene in a hospital serving
orphans. The artist aim was to convey welcoming and caring feelings to
abandoned children. The building is still there and still guests young
people that have committed some penalty. But the fresco was taken away
in 1920 and brought to the Uffizi museum. Once taken away from its
original context, it quickly became an object of exchange. And indeed,
this piece suffered damages with each travel.


This is the part that reminded me strongly of slavery: a fresco should
not travel for the simple reason that its nature is to be stuck on a
wall! If something, even a person, is taken away from its relations
and context, it is notably easier to put a price tag on that. In
Africa people were turned into slaves only after tearing them away
from their villages and families. Slaves have no identity, no roots.
The word free comes from German friend, and friends are what a slave
cannot have.

We people give value to things only after becoming aware of their
story. As soon as we give value to something, we struggle to give it a
price. [[https://en.wikipedia.org/wiki/Marie_Kondo][Marie Kondo]] expressly asks to abandon your feelings for pieces
in your wardrobe in order to unclutter it more freely. In many other
situations those same feelings of attachment are healthy because it
reflects that we value something.

When we assign a price to thing, or more simply we allow comparison,
we are making something a good for exchange.

Values and goods are fundamentally different and in a hierarchy with
each other: our values are the reason why we exchange things. So
people cannot ever be goods, because all we accomplish in life is for
other people. I write this because even if you are the most selfish
person, your are taking care of yourself, a person. And even if you
are the most generous person, for example dedicating your life to save
the environment, still you are taking care of other people.

The dignity of a person lies in not having a purpose. We people have
built a system to facilitate our existence in this world by quantify
the goods we need to live and with these numbers we distribute the
effort to acquire them. The economic system's aim is better living. A
better living requires the health and safety of other people, which
include for example both healthcare and culture. These are both
functional: healthcare takes care of your body while art takes care of
your identity and mind.

Nowadays I believe art requires more attention by us individuals
because technology is changing the world at a fast pace. Art can be an
antidote to this unstoppable change by holding to what will stay
unchanged: our human identity. All in all, people's desires will stay
the same no matter the tools with which they express them.

It is ironic that in pandemic times, which forced us to conduct our
lives in a more isolated manner, most governments easily shut museums
and theaters. This is affecting people's physical and mental health
and their immediate answer in many cases is palliative, taking pills
to handle the situation. Instead, museums and theaters can be tools
for understanding our togetherness. Pieces of art remind us of our
identity and dignity as human beings even if we are forcefully
restricted between four walls. Art can testify the emotions of people
of the past that also suffered in isolation and, so, remain relevant
and help us get through today's events.

Coincidentally, I had an interesting conversation about values with my
colleagues due to the Dutch housing market becoming incredibly
inaccessible. Roughly the average house in The Netherlands costs €300k
while the average salary is €58k and banks provide mortgage of about
3-5 times what you earn. So most of the population can barely afford a
mortgage, few houses are available which makes the competition raise
the price and the private rental market is unregulated (i.e.,
landlords can increase the rent each year with the percentage they
prefer).

Again I believe this is the result of losing track of the causal
relationship between values and goods. The economic system is going
against the dignity of people because it does not guarantee a space
for them to live in.

I believe that most of the wrongest problems in our society stem from
our blindness to this simple relationship between values and goods:
values have priority. Art can help us recognize those values clearly,
if we can interact with pieces of art and become aware of their
context and their story.

In summary anything we do as people is to take care of other people,
and this gives us dignity. The dignity of those that are born without
a purpose. Unconsciously the members of our society already spend
their lives caring about others. Absurdly enough we also reject the
immigrant or starve the poor or feel acceptable to let old people die
in oblivion rationalizing that would be too expensive to take care of
all these problems. Once more we confuse the relationship between
goods and values: we gather and transform resources to take care of
people because people are incomparable and the value of our society.
So the needs of people are the only reason to accumulate and expend
resources.

Luckily art testifies this. Any book, music, dance, painting, theater
scene is testifying a trait of our dignity. Each art form shows what
it means to be a person, elevating us to being one and projecting us
to produce more culture and slightly enriching what a person is with
our experience. As well as being a reflection of our dignity. Then I
feel that art itself is a value.
