#+TITLE:       Understanding ourselves: the miracle of sweat
#+AUTHOR:      Andrea
#+EMAIL:       andrea-dev@hotmail.com
#+DATE:        2021-11-13 Sat
#+URI:         /blog/%y/%m/%d/understanding-ourselves-the-miracle-of-sweat
#+KEYWORDS:    book, learning, growth
#+TAGS:        book, learning, growth
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: How sweat is an amazing feature of our bodies!

Sweat is the greatest miracle it could happen to our specie. Maybe it
is going to be our main mean of survival (again). Still we sank such a
miracle in the dirt of our insecurities. For profit.

This is heavily inspired by an interesting book I read recently: [[https://www.goodreads.com/book/show/55298348-the-joy-of-sweat?from_search=true&amp;from_srp=true&amp;qid=XmX8ROirH6&amp;rank=1#][The
Joy of Sweat by Sarah Everts]]. Sarah Everts is a science-journalist and
did an amazing job at bringing clarity about what sweat is.

Sweat always reminds me of the negative remarks of my (female) family
members. "You smell! Go washing yourself" or "you really need some
deodorant". In hindsight, I must say that these comments really
happened only in my family. Other close people would not remark about
that, even when I curiously asked about it. That stayed a mystery
until the other day.

We are going to get Darwinian pretty fast here, so get ready. There is
a reason why [[https://optimistminds.com/what-family-members-can-you-marry-in-the-uk/][you cannot (by law) marry a close family member]]. The
children of a couple of close family members will (have greater
chances to) be at disadvantage against diverse couples. For example,
[[https://en.wikipedia.org/wiki/Blue_Fugates][they may develop blue skin]]. This may seem far from our sweat issues,
but survival does not wait for human laws, right? Our body needed a
way to avoid procreating with somebody too similar to us. The eyes
don't work here because it is easy to trick our main sensors! But
smell...

Claus Wedekind in 1995 showed that women can pick partners that carry
a compatible immune system via smell. Yin Yang kind of compatible. His
experiment required some smelly t-shirts, but women found partners
with an immune system complementing theirs. If you find that
surprising, there is more: did you realize that greetings between
people (pre-COVID) are always in "nose-proximity"? It seems we do use
this sense a lot (subconsciously)!

To return to my family, my conjecture is that I got told off by my
female family members for a (very good) reason! They perceived me very
smelly because their body was screaming that I was the worst possible
partner for them.

Now let's get into deodorants a moment. We live in a capitalist
system. The best way to sell something is to make another person feel
they need it. So we just said that smell makes you find the best
(immune system) partner available. But there is nothing to sell like
this! Time to make you feel insecure: "men/women will not like you if
you smell so badly: rather buy this product to attract them". It
worked. A bit too well. To the point that sweat makes some people feel
guilty. Sure, if you don't like somebody else's smell, it may be
unbearable. Still, we must not shame others because they are who they
are. (Also, try to get a whiff of your partner real smell if you are
looking for the best immune system for your children -- that sounds so
'eugenetics' :).

Anyway, let's move onto why (most) people have hair on their heads.
It's still about sweat. I think you are reading this on a digital
device. Maybe you know that if your device overheats a lot, it will
stop working (if not exploding). If you observed dogs in summer, you
may have seen they overheat too. Typically they throw their tongue out
and start shallow breathing. Also a computer does something similar:
you typically hear the fan when that happens. The dog is more
efficient at it. We win though.

The computer is not good. The fan moves just air. The dog is so so:
the breath moves air but also water! The saliva on the tongue but also
the water from their lungs. And us?!? We are pros thanks to: sweat!

Evaporation. I guess there is a reason why [[https://en.wikipedia.org/wiki/List_of_water_deities][we dedicated so many gods
to water]]. Water exploding into vapour (its gas form) disperse heat!
[[https://youtu.be/HaeDkw2iKHg?t=57][Somebody even made a product from that]]. Bet what we expel from our
bodies? Well, it is blood not water. Sweat is really blood filtered of
(most) useful minerals. We really don't manage to retain all the
minerals (too much effort) and that is why our sweat is salty. That is
also why sweating is not releasing impurities (the kidneys are). Sauna
is not a detox, sorry. On the other hand, Sauna is a great training
for the heart to avoid strokes!

Since we are speaking of saunas, let's see the miracle: [[https://www.youtube.com/watch?v=vojNDIu7uIE&t=49s][in this video]],
a person enters in a sauna filmed with a thermal camera. The miracle
appears when he exits the sauna: his body is in a darker color than
the sauna. That means it is colder. When you put a potato in a warm
oven, the potato will reach the oven temperature. A human will not
until he is dead. Its sweat will shield a person from the heat by
dissipating it. We defeat physics! Well.. we make the best out of
physics!

But why? What is the reason for this amazing feature (we became so
ashamed of)?

We know that devices don't like saunas. So think again about the dog.
A dog dissipates heat from its mouth. That is not going to work in a
sauna because the heat is too great. Its hair is also insulating the
dog! So the internal heat cannot escape quick enough.

Next, dogs were once wolfs. And what is comparable to a sauna for
internal heat? Prolonged physical exercise. If wolves were to run for
a very long time, they would overheat. So they need to stop
eventually. What about us? We would just blood out. Our sweat
guarantees we don't overheat. (Still, two things can go wrong: not
enough water in our body or too high intensity movement. This causes
heart failure.) [[https://www.youtube.com/watch?v=826HMLoiE_o&t=181s][This documentary]] is a proof of how we used our unique
resilience skills to make a living. And by the way, you know when you
get nervous and your hands sweat? That may make you feel sticky and
stress you out, but hear this: say that instead of your boss starting
to tell you off there was a wolf in front of you, what do you think
are you doing in a second from now? Right run at full speed. What
happens when you run at full speed? You (and the wolf) heat up. What
do you do to cool down? You sweat, the wolf shallow breathes. But you
start sweating before: wet hands remember? Your body cools down early!
It prepares you for the sprint. This is just too cool! In modern days
our stress does not mean we will sprint. We end up even more stressed
out because we are wetting the desk, and others may notice. For
serious situations though, what a great feature!
                                                                       
And a final question for you dear reader: in the previous video, where
was the (midday/hottest) Sun hitting the running man? On the head!
Indeed, that is the only place that is most exposed to the Sun's heat
when we stand. That is why it is still worth insulating with hair. I
guess, that way we save sweat (like when the people dress in the
desert).

That is just a portion of the beautiful things I read in that book!
How unappreciated is our body! How preposterous our insecurities. Next
time you smell somebody, think (also) how clever is that mechanism!

And when climate change hits, sweat may gives us a chance at survival
(again).

Happy sweating!
