#+TITLE:       What if we cannot make it? A less optimistic view on climate change
#+AUTHOR:      Andrea
#+EMAIL:       andrea-dev@hotmail.com
#+DATE:        2021-07-27 Tue
#+URI:         /blog/%y/%m/%d/what-if-we-cannot-make-it-a-less-optimistic-view-on-climate-change
#+KEYWORDS:    energy, society, design, failure, learning, growth
#+TAGS:        energy, society, design, failure, learning, growth
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: Are we parasites or gardeners?

I strongly believe in people. Once I had to sleep in a hostel for a
few months in a shared room. Then I was short on money. One day one of
my roommates asks me a favour: could I borrow him about half of the
money I had available? He didn't know how much that was for me at the
time. I did. I was about to reject him, when I remember to have
thought: "I want to trust humanity". I am happy of having done that. I
have been lucky multiple times with humanity. That makes my optimism
founded on (personal) statistics.

I have an issue with my society though. [[https://goodreads.com/book/show/39282904-wardley-maps?from_search=true&amp;from_srp=true&amp;qid=VBcLU2CtDi&amp;rank=1][In the words of Simon Wardley]]:
"Most competitors have poor situational awareness". Well, he was
writing about companies, but I think that is fitting for people and
their environment too. [[https://en.wikipedia.org/wiki/Tragedy_of_the_commons#Solutions][The tragedy of the commons]] stems from a lack of
situational awareness: if we were to know that cutting more than 8 of
our 10 trees available condemns us all to death, but weren't aware of
the trees left by our neighbours and we needed their wood, we would
have little chances of survival.

What if we had already cut the 9th tree?

The fact I don't hear this discussed on the newspaper worries me. When
I read headlines like "Germany is flooded", it still sounds like we
are seeing the first signs of climate change in action. My aim is not
to have more catastrophic news, but to start a discussion about what
is the role of people on this planet.

I guess if I were a gardener and my garden mostly died of a sickness,
I would spend my energies into facilitate its regeneration. In my
previous example, we would be behaving more like a sickness than a
gardener. We cut 9 trees out of 10, so we are condemned: what shall we
invest our little time left into?

That is not a rhetorical question. This question is to define what is
important for us as a species. Given we have lost everything already,
what are we left to do with our lives?

This is not (just) a philosophical question either, because it seems
pretty actual. I share the view that we are relying on technology too
much to solve our sustainability issue (with a [[https://www.youtube.com/watch?v=Zk11vI-7czE][few]] [[https://www.youtube.com/watch?v=1Q5CXN7soQg][documentaries]] I
watched recently). There the point made is that solar, wind and
biomass are viable only if we burn coal, gas and oil: how could we
maintain or build one of those huge wind turbines relying on renewable
energy that produce intermittently (producing batteries also rely
heavily on fossil fuel...)?

The principle convinces me more than the facts: technology is just a
tool we develop for our aim. When we aimed to hunt animals we
developed knives and arcs. When we wanted to move faster we developed
horse riding and engines. When we wanted to keep living with high
energy consumption, we made up solar panels, wind turbines and biomass
(a.k.a., burning trees).

If we lack situational awareness, we could create a technology that
does not help us. Simply because we don't know what is the problem.

Let me be concrete. Years ago I decided to improve my finances. The
driving idea was to give myself the economical tools to make a
difference in sustainable living (I am slowly getting there I hope). I
looked around for options to do that. The majority of Internet results
pointed me to investments. Now I read Pinocchio and I am familiar with
the risks of planting money. I am not referring to the dividends of
the stock market (although Graham makes a similar point about
speculating in [[https://www.goodreads.com/book/show/106835.The_Intelligent_Investor?from_search=true&from_srp=true&qid=szWQEN2y4K&rank=1][The intelligent investor]]), rather at their effects on
the planet I live. If my super safe index fund will invest in the
companies that deteriorate this world, I am destroying the world by
trying to improve my finances. So what then? In my case I gave credit
to the alternative view: improve situational awareness. I worked on
making visible where I was spending my earnings. Then I drastically
reduced those expenses that were both causing nasty effects to others
and&or unneeded. This approach works for me.

The problem is still what are those finances I want to improve for? I
would say that even before being at the 9th tree, my aim should be to
make impossible to cut the 8th tree. My aim should be to make my
resources inextinguishable. As for my ledger, or I earn more or I
decrease spending. Do both at the same time and we are on the right
path to have a place and wealth we can share with others.

I get vibes that we, instead, are starting to cut the 9th tree blind
to our problem. We are sort of thinking: "I feel this is maybe the
last tree, but if I cut it I can make this tool to make this tree's
wood last longer". I mean take the Covid-19 pandemic as an example: [[https://www.inquirer.com/science/climate/earth-day-coronavirus-philadelphia-wildlife-pollution-climate-change-20200422.html][we
have seen nature flourish for the lack of human intervention]], and we
have been craving to be back on a plane to go for holidays. Or better
still, take the examples of the billionaires competing to
[[https://www.bbc.co.uk/news/science-environment-57797297][commercialize]] [[https://edition.cnn.com/2021/07/20/tech/jeff-bezos-blue-origin-launch-scn/index.html][space]]. Are we planning to abandon our garden? Are we
identifying ourselves as galactic parasites? I thought parasitic
aliens were evil in movies.

I would find it romantic if we both perished or survived while
attempting to restore our wrong doings. It would be ideal to become
the guardians of Earth because we can. "With Great Power Comes Great
Responsibility", remember? We have an intellect, we are alive and so
we depend on the balance of our ecosystem. We became so many that our
hosting ecosystem depends on us too. In theory we check all the boxes
to satisfy our hanger and grow the planet to a new splendor of life.
They are the same boxes that we check for destroying our existence on
it.

So say it is too late. Say that there is just a tomorrow, but not a
day after. What is going to be your last day about?

I wish your answer brings hope to everyone and peace of mind to
yourself.
